import re
from fpdf import FPDF

def sanitize_text(text):
    if not text:
        return ""
    # Map common unicode characters to latin-1/ASCII
    replacements = {
        "₹": "Rs. ",
        "–": "-",
        "—": "-",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "•": "*",
        "·": "*",
        "é": "e",
        "á": "a",
        "í": "i",
        "ó": "o",
        "ú": "u",
        "ñ": "n",
        "™": "TM",
        "©": "(c)",
        "®": "(r)"
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
        
    # Remove emojis and other characters that cannot be encoded in Latin-1
    sanitized = []
    for char in text:
        try:
            char.encode("latin-1")
            sanitized.append(char)
        except UnicodeEncodeError:
            # Skip emoji or unsupported char
            continue
    return "".join(sanitized)

class ItineraryPDF(FPDF):
    def __init__(self, destination, days, style, interests):
        super().__init__()
        self.destination = sanitize_text(destination)
        self.days = str(days)
        self.style = sanitize_text(style)
        self.interests = sanitize_text(interests) if interests else None

    def header(self):
        # Draw elegant deep indigo header banner
        self.set_fill_color(30, 27, 75)  # #1e1b4b (Deep Indigo)
        self.rect(0, 0, 210, 42, "F")
        
        # Border glow line (violet accent)
        self.set_fill_color(99, 102, 241)  # #6366f1 (Indigo/Violet Accent)
        self.rect(0, 42, 210, 2, "F")
        
        # Title text
        self.set_y(10)
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 18)
        self.cell(0, 10, "AI TRAVEL CONCIERGE", align="C", new_x="LMARGIN", new_y="NEXT")
        
        # Subtitle
        self.set_font("helvetica", "I", 10)
        self.set_text_color(226, 232, 240)  # #e2e8f0
        self.cell(0, 6, "Your Personalized Day-by-Day Travel Guide", align="C", new_x="LMARGIN", new_y="NEXT")
        
        # Reset position and text color for page content
        self.set_y(50)
        self.set_text_color(15, 23, 42)  # #0f172a (Slate Dark)

    def footer(self):
        # Position footer at 15 mm from bottom
        self.set_y(-15)
        self.set_text_color(148, 163, 184)  # #94a3b8
        self.set_font("helvetica", "I", 8)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by AI Travel Concierge", align="C")

def generate_itinerary_pdf(destination, days, style, interests, itinerary_text):
    # Initialize PDF in A4, Portrait
    pdf = ItineraryPDF(destination, days, style, interests)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Metadata / Cover Card Section
    pdf.set_fill_color(248, 250, 252) # #f8fafc (Sleek light card background)
    pdf.rect(10, 50, 190, 32, "F")
    
    # Border for the metadata card
    pdf.set_draw_color(226, 232, 240) # #e2e8f0
    pdf.rect(10, 50, 190, 32, "D")
    
    # Metadata Text
    pdf.set_xy(15, 53)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(30, 27, 75)
    pdf.cell(0, 6, f"Trip to: {pdf.destination}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(71, 85, 105) # #475569
    pdf.cell(0, 5, f"Duration: {pdf.days} Days  |  Travel Style: {pdf.style}", new_x="LMARGIN", new_y="NEXT")
    if pdf.interests:
        pdf.cell(0, 5, f"Special Interests: {pdf.interests}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(18)
    
    # Process itinerary text
    sanitized_text = sanitize_text(itinerary_text)
    
    days_data = re.split(r"(?i)##?\s*Day\s*(\d+)", sanitized_text)
    
    # If there is intro text
    if len(days_data) > 1 and days_data[0].strip():
        intro = days_data[0].strip()
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.multi_cell(0, 5, intro, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        
    # Render each day
    if len(days_data) > 1:
        for i in range(1, len(days_data), 2):
            day_num = days_data[i]
            day_content = days_data[i+1].strip()
            # Clean up leading punctuation from day_content
            day_content = re.sub(r"^[:\s\-]*", "", day_content)
            
            # Check page break space (ensure page doesn't break right after the header)
            if pdf.get_y() > 240:
                pdf.add_page()
            
            # Draw Day Header bar
            pdf.set_fill_color(79, 70, 229)  # #4f46e5 (Indigo Accent)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("helvetica", "B", 11)
            # Create a full-width header cell
            pdf.cell(0, 8, f"  DAY {day_num}", fill=True, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
            
            # Print content for this day
            pdf.set_text_color(15, 23, 42)
            pdf.set_font("helvetica", "", 10)
            
            # Print lines
            lines = day_content.split("\n")
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                # If it's a subheader within a day (e.g. ### Morning:)
                if line.startswith("###") or line.startswith("##"):
                    pdf.ln(1)
                    pdf.set_font("helvetica", "B", 10)
                    cleaned_line = line.lstrip("#").strip()
                    pdf.cell(0, 6, cleaned_line, new_x="LMARGIN", new_y="NEXT")
                    pdf.set_font("helvetica", "", 10)
                else:
                    # Multi-line cell for bullet points or paragraphs
                    pdf.multi_cell(0, 5, line, new_x="LMARGIN", new_y="NEXT")
            
            pdf.ln(6)
    else:
        # Fallback if parsing fails, print entire sanitized text
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.multi_cell(0, 5, sanitized_text, new_x="LMARGIN", new_y="NEXT")
        
    # Output raw PDF bytes
    pdf_bytes = pdf.output()
    if isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode("latin-1")
    return bytes(pdf_bytes)
